spring:
  application:
    name: catalog-service

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081