"""add info_type to rumor_signal

Revision ID: 09e84e23823e
Revises: 195d80f9dde3
Create Date: 2026-07-28 19:27:33.159844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e84e23823e'
down_revision: Union[str, Sequence[str], None] = '195d80f9dde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE information_type_enum AS ENUM ('RELEASE_DATE_CHANGE', 'RUMOR', 'UNRELATED')")
    op.add_column('rumor_signal', sa.Column('info_type', sa.Enum('RELEASE_DATE_CHANGE', 'RUMOR', 'UNRELATED', name='information_type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rumor_signal', 'info_type')
    op.execute("DROP TYPE information_type_enum")
    # ### end Alembic commands ###
