"""add rumor trend snapshot

Revision ID: 609c6fcaf3ff
Revises: 4ee635dbf2cb
Create Date: 2026-08-20 20:48:25.953063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609c6fcaf3ff'
down_revision: Union[str, Sequence[str], None] = '4ee635dbf2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rumor_trend_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_item_id', sa.UUID(), nullable=False),
    sa.Column('delay_probability', sa.Numeric(), nullable=False),
    sa.Column('signal_count', sa.Numeric(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rumor_trend_snapshot_media_item_id'), 'rumor_trend_snapshot', ['media_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rumor_trend_snapshot_media_item_id'), table_name='rumor_trend_snapshot')
    op.drop_table('rumor_trend_snapshot')
    # ### end Alembic commands ###
