"""add extracted_release_date to rumor_signal

Revision ID: 778f66abaf29
Revises: 609c6fcaf3ff
Create Date: 2026-08-20 20:52:03.646395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778f66abaf29'
down_revision: Union[str, Sequence[str], None] = '609c6fcaf3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rumor_signal', sa.Column('extracted_release_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rumor_signal', 'extracted_release_date')
    # ### end Alembic commands ###
