"""Initial migration

Revision ID: d78f6814ac46
Revises:
Create Date: 2026-07-28 15:49:35.421631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78f6814ac46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rumor_signal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_item_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_reputation_score', sa.Numeric(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(), nullable=False),
    sa.Column('mentions_delay', sa.Boolean(), nullable=False),
    sa.Column('evaluation_confidence', sa.Numeric(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rumor_signal_media_item_id'), 'rumor_signal', ['media_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rumor_signal_media_item_id'), table_name='rumor_signal')
    op.drop_table('rumor_signal')
    # ### end Alembic commands ###
