"""add media outcome and known release date to delay probability history

Revision ID: ef66a184118c
Revises: 778f66abaf29
Create Date: 2026-08-27 14:00:32.928800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef66a184118c'
down_revision: Union[str, Sequence[str], None] = '778f66abaf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_outcome',
    sa.Column('media_item_id', sa.UUID(), nullable=False),
    sa.Column('actual_release_date', sa.Date(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('media_item_id')
    )
    op.add_column('delay_probability_history', sa.Column('known_release_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delay_probability_history', 'known_release_date')
    op.drop_table('media_outcome')
    # ### end Alembic commands ###
