spring:
  application:
    name: core-service

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/umt}

tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY:}

server:
  port: 8081